# Generated by Django 4.0.6 on 2022-07-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficio.address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('person_type', models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1)),
                ('doc_number', models.CharField(max_length=14)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_in', models.DateField()),
                ('ol_date', models.DateField()),
                ('ol_origin_id', models.CharField(max_length=50)),
                ('lawsuit_number', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('received_ol_number', models.CharField(max_length=50)),
                ('answer_ol', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority', to='oficio.authority')),
                ('lawsuit_part_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_received_ol', to='oficio.person')),
                ('lawsuit_part_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accused_received_ol', to='oficio.person')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('lawsuit_number', models.CharField(max_length=50)),
                ('answer', models.TextField()),
                ('sent_ol_number', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_to_ol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficio.receivedol')),
                ('authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficio.authority')),
                ('lawsuit_part_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_sent_ol', to='oficio.person')),
                ('lawsuit_part_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accused_sent_ol', to='oficio.person')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='oficio.state')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='oficio.city'),
        ),
    ]
