# Generated by Django 4.0.6 on 2022-07-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0002_address_authority_person_receivedol_state_sentol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
