# Generated by Django 4.0.6 on 2022-07-10 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0003_alter_address_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='receivedol',
            name='lawsuit_part_one',
        ),
        migrations.RemoveField(
            model_name='receivedol',
            name='lawsuit_part_two',
        ),
        migrations.RemoveField(
            model_name='sentol',
            name='lawsuit_part_one',
        ),
        migrations.RemoveField(
            model_name='sentol',
            name='lawsuit_part_two',
        ),
        migrations.AddField(
            model_name='authority',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='complement',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='oficio.state'),
        ),
        migrations.AddField(
            model_name='receivedol',
            name='accused_doc_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='receivedol',
            name='accused_type',
            field=models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1),
        ),
        migrations.AddField(
            model_name='receivedol',
            name='author_doc_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='receivedol',
            name='author_type',
            field=models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1),
        ),
        migrations.AddField(
            model_name='receivedol',
            name='lawsuit_accused',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receivedol',
            name='lawsuit_author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sentol',
            name='accused_doc_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='sentol',
            name='accused_type',
            field=models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1),
        ),
        migrations.AddField(
            model_name='sentol',
            name='author_doc_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='sentol',
            name='author_type',
            field=models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1),
        ),
        migrations.AddField(
            model_name='sentol',
            name='lawsuit_accused',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sentol',
            name='lawsuit_author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='lawsuit_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
