# Generated by Django 4.0.6 on 2022-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0004_remove_city_state_remove_receivedol_lawsuit_part_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='complement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
