# Generated by Django 4.0.6 on 2022-07-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0005_alter_authority_address_alter_authority_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedol',
            name='received_in',
            field=models.DateField(verbose_name='Recebido em'),
        ),
    ]
