# Generated by Django 4.0.6 on 2022-07-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0006_alter_receivedol_received_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedol',
            name='accused_doc_number',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='accused_type',
            field=models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='answer_ol',
            field=models.CharField(max_length=50, verbose_name='Número do Ofício Resposta'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='author_doc_number',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='author_type',
            field=models.IntegerField(choices=[(1, 'PF'), (2, 'PJ')], default=1, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority', to='oficio.authority', verbose_name='Autoridade Emitente'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='deadline',
            field=models.DateField(verbose_name='Prazo para Resposta'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='lawsuit_accused',
            field=models.CharField(max_length=200, null=True, verbose_name='Réu'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='lawsuit_author',
            field=models.CharField(max_length=200, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='lawsuit_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Processo nº:'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='ol_date',
            field=models.DateField(verbose_name='Data do Ofício'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='ol_origin_id',
            field=models.CharField(max_length=50, verbose_name='Número ou Identificação do Ofício'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='received_ol_number',
            field=models.CharField(max_length=50, verbose_name='Número do Ofício Recebido'),
        ),
    ]
