# Generated by Django 4.0.6 on 2022-07-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0007_alter_receivedol_accused_doc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedol',
            name='accused_doc_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='answer_ol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Ofício Resposta'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='author_doc_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority', to='oficio.authority', verbose_name='Autoridade Emitente'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='lawsuit_accused',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Réu'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='lawsuit_author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='lawsuit_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Processo nº:'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='ol_origin_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número ou Identificação do Ofício'),
        ),
        migrations.AlterField(
            model_name='receivedol',
            name='received_ol_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Ofício Recebido'),
        ),
    ]
