# Generated by Django 4.0.6 on 2022-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0010_alter_authority_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentol',
            name='accused_doc_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ'),
        ),
    ]
