# Generated by Django 4.0.6 on 2022-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0011_alter_sentol_accused_doc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentol',
            name='creation_date',
            field=models.DateField(verbose_name='Data de Elaboração'),
        ),
    ]
